name:                stack-playground
version:             1.3.3.7
github:              "googleson78/playground"
author:              "Georgi Lyubenov"
maintainer:          "georgi.lyubenov@chaosgroup.com"
copyright:           "2018 Georgi Lyubenov"

description:         ex nihilo

dependencies:
- base >= 4.7 && < 5
- threepenny-gui
- stm
- containers

library:
  source-dirs: src

executables:
  main:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stack-playground

tests:
  tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stack-playground
